// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC775deRaxPivvAB8oS5KQhJel99jd6vd8',
    appId: '1:221689759358:android:0627676b25de35245dfa2f',
    messagingSenderId: '221689759358',
    projectId: 'flashfeed-8fc75',
    storageBucket: 'flashfeed-8fc75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkfqGKG5F0yf44tg3P02PL8dvJgeFgzfs',
    appId: '1:221689759358:ios:21869fa0972f27dc5dfa2f',
    messagingSenderId: '221689759358',
    projectId: 'flashfeed-8fc75',
    storageBucket: 'flashfeed-8fc75.firebasestorage.app',
    androidClientId: '221689759358-h8p0nluh8g4cn41rlfumgotsqd587ibt.apps.googleusercontent.com',
    iosClientId: '221689759358-e1h9p2nkod91a045bjhmbbaf33eqbb29.apps.googleusercontent.com',
    iosBundleId: 'com.coditas.routiner',
  );
}
